apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: counter-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    project: counter
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.host }}-tls
  rules:
    - host: {{ required ".Values.host is required" .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: counter-frontend
                port:
                  number: 80
